theme: jekyll-theme-slate
title: Social Monitoring Through Sentiment Analysis And Topic Modeling For Food Delivery Platforms
description: An End-to-end Machine Learning Application To Extract Emotions And Topics From Twitter Data
